; Este é um arquivo de configuração
; Comentários iniciam com ';', como no php.ini

driver = "mysql";certo
server = "162.241.2.84";certo
user = "gusta316_swmai";certo
password = "vgdYc5E73KCcT6e";certo
database = "gusta316_SWMAI";certo
port = "3306";certo
debug = "false";certo