; Este é um arquivo de configuração
; Comentários iniciam com ';', como no php.ini

driver = "pgsql";
server = "localhost";
user = "postgres";
password = "postdba";
database = "dws2_gusta";
port = "5433"; porta do PostgreSQL17
debug = "true";