; Este é um arquivo de configuração
; Comentários iniciam com ';', como no php.ini

driver = "SECRET";
server = "SECRET";
user = "SECRET";
password = "SECRET";
database = "SECRET";
port = "SECRET"; 
debug = "true";
